import {
  IconAlertTriangle,
  IconArmchair,
  IconBook,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconEdit,
  IconEye,
  IconEyeOff,
  IconInfoCircle,
  IconInbox,
  IconLoader2,
  IconLogout,
  IconMenu2,
  IconMessageCircle,
  IconPlus,
  IconSearch,
  IconSettings,
  IconTool,
  IconTrash,
  IconUsers,
  IconX,
  IconHome,
  IconBell,
  IconPhone,
  IconMail,
  IconUpload,
  IconDownload,
  IconRefresh,
  IconFilter,
  IconDotsVertical,
  IconCopy,
  IconExternalLink,
  IconChevronUp,
  IconArrowLeft,
  IconArrowRight,
  IconCircleCheck,
  IconCircleX,
  IconUser,
  IconMapPin,
  IconCurrencyDollar,
  IconMessage,
  IconSun,
  IconMoon,
  IconBrandGoogleDrive,
  IconBrandSlack,
  IconMessages,
  IconSend,
  type IconProps,
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // Navigation
  home: IconHome,
  calendar: IconCalendar,
  users: IconUsers,
  settings: IconSettings,
  whatsapp: IconMessageCircle,
  analytics: IconArmchair,
  knowledgeBase: IconBook,
  services: IconTool,
  notifications: IconBell,
  sun: IconSun,
  moon: IconMoon,
  messages: IconMessages,

  // Actions
  logout: IconLogout,
  menu: IconMenu2,
  close: IconX,
  search: IconSearch,
  add: IconPlus,
  edit: IconEdit,
  delete: IconTrash,
  check: IconCheck,
  checkCheck: IconChecks,
  eye: IconEye,
  eyeOff: IconEyeOff,
  upload: IconUpload,
  download: IconDownload,
  refresh: IconRefresh,
  filter: IconFilter,
  copy: IconCopy,
  externalLink: IconExternalLink,
  send: IconSend,

  // Navigation arrows
  chevronDown: IconChevronDown,
  chevronUp: IconChevronUp,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,

  // Contact
  phone: IconPhone,
  mail: IconMail,
  googleDrive: IconBrandGoogleDrive,
  slack: IconBrandSlack,

  // UI / Feedback
  spinner: IconLoader2,
  warning: IconAlertTriangle,
  info: IconInfoCircle,
  inbox: IconInbox,
  dotsVertical: IconDotsVertical,
  circleCheck: IconCircleCheck,
  circleX: IconCircleX,

  user: IconUser,
  mapPin: IconMapPin,
  currencyDollar: IconCurrencyDollar,
  message: IconMessage,
  plus: IconPlus,
  trash: IconTrash,
} as const;

export type IconName = keyof typeof Icons;
